on:
  push:
    branches:
      - '*'
      - '!gh-pages/*'
      - '!releases/*'
name: ci-build

jobs:
  matrix-build:
    name: build_${{ matrix.node_version }}_${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [10, 12]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: checkout code
        uses: actions/checkout@v1
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          version: ${{ matrix.node_version }}
      - run: npm ci
      - run: npm run build
      - if: matrix.os != 'windows-latest'
        # On windows, the file paths are modified, causing CI build failures.
        # For github-actions, it might not be an issue. So we document and leave it alone
        run: npm run bundled
